# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/ISE/3380_G29/Project_P2/project_2/project_2.cache/wt [current_project]
set_property parent.project_path T:/ISE/3380_G29/Project_P2/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/full_adder2.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/MUX312.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/and_gate2.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/or_gate2.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/ALU4.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/new/JMP_Concat.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/Signextend1.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/Registers2.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/PC_REG.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/mux3_11.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/mux2_11.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/Memory.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/Control1.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/ALU_16Bit3.vhd
  T:/ISE/3380_G29/Project_P2/project_2/project_2.srcs/sources_1/imports/project_part1/CPU_33802.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top CPU_3380 -part xc7a100tcsg324-2


write_checkpoint -force -noxdef CPU_3380.dcp

catch { report_utilization -file CPU_3380_utilization_synth.rpt -pb CPU_3380_utilization_synth.pb }
